CREATE TABLE players 
(
    first_name	varchar(300),
    last name	varchar(300),
    country	varchar(300),
    id_player	varchar(300),
    id_team	varchar(300)
);

INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Faythe', 'Bruton', 'Faroe Islands', 'PLR101', 'T-9001');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Way', 'Axelbey', 'Malaysia', 'PLR102', 'T-9002');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Ivette', 'Roe', 'Indonesia', 'PLR103', 'T-9003');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Constantine', 'Comrie', 'Libya', 'PLR104', 'T-9004');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Peria', 'Tripney', 'China', 'PLR105', 'T-9005');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Charmian', 'Hecks', 'Portugal', 'PLR106', 'T-9006');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Velvet', 'Danielou', 'Indonesia', 'PLR107', 'T-9007');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Devondra', 'Costello', 'Ukraine', 'PLR108', 'T-9008');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Kirby', 'Momery', 'Argentina', 'PLR109', 'T-9009');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Danella', 'Beuscher', 'France', 'PLR110', 'T-9010');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Erica', 'Bradbeer', 'Honduras', 'PLR111', 'T-9011');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Yorke', 'Stuttard', 'Ukraine', 'PLR112', 'T-9012');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Gavrielle', 'Davidov', 'Russia', 'PLR113', 'T-9013');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Rickie', 'Cribbins', 'Czech Republic', 'PLR114', 'T-9014');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Viole', 'Kiljan', 'Portugal', 'PLR115', 'T-9015');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Bron', 'Petruk', 'Argentina', 'PLR116', 'T-9016');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Merl', 'Auld', 'Peru', 'PLR117', 'T-9017');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Adey', 'Gowenlock', 'Mongolia', 'PLR118', 'T-9018');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Elia', 'Kilborn', 'Belize', 'PLR119', 'T-9019');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Cletis', 'Narbett', 'Finland', 'PLR120', 'T-9020');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Monika', 'Acres', 'Indonesia', 'PLR121', 'T-9021');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Hersch', 'Hache', 'Indonesia', 'PLR122', 'T-9022');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Gus', 'Whetton', 'Samoa', 'PLR123', 'T-9023');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Harrietta', 'Allward', 'Canada', 'PLR124', 'T-9024');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Nedda', 'Lacy', 'Indonesia', 'PLR125', 'T-9025');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Marlene', 'Bertouloume', 'China', 'PLR126', 'T-9026');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Alix', 'Omond', 'Burkina Faso', 'PLR127', 'T-9027');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Allard', 'Heinonen', 'Venezuela', 'PLR128', 'T-9028');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Eleen', 'Suerz', 'United States', 'PLR129', 'T-9029');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Fransisco', 'Jentzsch', 'Czech Republic', 'PLR130', 'T-9030');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Stacia', 'Elven', 'Indonesia', 'PLR131', 'T-9031');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Stephan', 'Zemler', 'Barbados', 'PLR132', 'T-9032');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Brady', 'Stempe', 'China', 'PLR133', 'T-9033');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Bertram', 'Tibbotts', 'Japan', 'PLR134', 'T-9034');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Kira', 'Kyteley', 'France', 'PLR135', 'T-9035');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Sallyanne', 'Hiom', 'China', 'PLR136', 'T-9036');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Emili', 'Burner', 'China', 'PLR137', 'T-9037');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Othelia', 'Saffin', 'France', 'PLR138', 'T-9038');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Sheila', 'Bearblock', 'Mexico', 'PLR139', 'T-9039');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Antonella', 'Lemmer', 'France', 'PLR140', 'T-9040');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Solly', 'Dinwoodie', 'China', 'PLR141', 'T-9041');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Maynord', 'Girone', 'Nigeria', 'PLR142', 'T-9042');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Moll', 'Kelk', 'South Korea', 'PLR143', 'T-9043');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Lucio', 'Skillicorn', 'Azerbaijan', 'PLR144', 'T-9044');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Raye', 'Corter', 'Indonesia', 'PLR145', 'T-9045');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Rutter', 'Verna', 'Honduras', 'PLR146', 'T-9046');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Immanuel', 'Shallcross', 'Malaysia', 'PLR147', 'T-9047');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Calvin', 'Martinuzzi', 'China', 'PLR148', 'T-9048');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Raquel', 'De Brett', 'China', 'PLR149', 'T-9049');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Englebert', 'Chattell', 'South Korea', 'PLR150', 'T-9050');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Byran', 'O\'Codihie', 'Cambodia', 'PLR151', 'T-9051');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Reade', 'Habishaw', 'China', 'PLR152', 'T-9052');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Cynthia', 'Allerton', 'China', 'PLR153', 'T-9053');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Othella', 'Eynald', 'China', 'PLR154', 'T-9054');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Jaymie', 'Jollye', 'Ivory Coast', 'PLR155', 'T-9055');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Stavros', 'Riddlesden', 'Brazil', 'PLR156', 'T-9056');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Caesar', 'Orneles', 'Portugal', 'PLR157', 'T-9057');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Jorie', 'Van Weedenburg', 'China', 'PLR158', 'T-9058');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Tabitha', 'Do Rosario', 'China', 'PLR159', 'T-9059');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Stormy', 'Reddish', 'Brazil', 'PLR160', 'T-9060');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Mary', 'Brannon', 'Netherlands', 'PLR161', 'T-9061');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Jedd', 'le Keux', 'Madagascar', 'PLR162', 'T-9062');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Jess', 'McComish', 'China', 'PLR163', 'T-9063');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Grace', 'Scollard', 'Philippines', 'PLR164', 'T-9064');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Trent', 'Lytlle', 'Indonesia', 'PLR165', 'T-9065');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Bridie', 'Harmar', 'Russia', 'PLR166', 'T-9066');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Ardisj', 'Touzey', 'Brazil', 'PLR167', 'T-9067');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Tommie', 'Purchall', 'France', 'PLR168', 'T-9068');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Jackson', 'Dalglish', 'China', 'PLR169', 'T-9069');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Meaghan', 'Baughn', 'United States', 'PLR170', 'T-9070');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Rhianna', 'Redfearn', 'Jamaica', 'PLR171', 'T-9071');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Emlyn', 'Juppe', 'Philippines', 'PLR172', 'T-9072');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Shelley', 'Svanetti', 'Morocco', 'PLR173', 'T-9073');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Rubina', 'Mulliner', 'Czech Republic', 'PLR174', 'T-9074');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Kingsley', 'Tizard', 'Indonesia', 'PLR175', 'T-9075');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Nikkie', 'Waterworth', 'Argentina', 'PLR176', 'T-9076');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Karlan', 'Dongles', 'China', 'PLR177', 'T-9077');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Marita', 'Mullarkey', 'Poland', 'PLR178', 'T-9078');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Davine', 'O\' Mullane', 'Mexico', 'PLR179', 'T-9079');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Johan', 'De Vuyst', 'Portugal', 'PLR180', 'T-9080');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Korella', 'Beyn', 'Sweden', 'PLR181', 'T-9081');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Taffy', 'Ilem', 'China', 'PLR182', 'T-9082');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Cherie', 'Thing', 'China', 'PLR183', 'T-9083');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Joline', 'Realy', 'Greece', 'PLR184', 'T-9084');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Jessie', 'Beake', 'Czech Republic', 'PLR185', 'T-9085');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Pansie', 'Garrettson', 'China', 'PLR186', 'T-9086');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Anders', 'Manners', 'Argentina', 'PLR187', 'T-9087');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Harrie', 'Grinter', 'Portugal', 'PLR188', 'T-9088');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Charyl', 'Scopham', 'Serbia', 'PLR189', 'T-9089');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Ezra', 'Fourcade', 'Colombia', 'PLR190', 'T-9090');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Waneta', 'Ceaplen', 'Greece', 'PLR191', 'T-9091');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Oona', 'Heisman', 'China', 'PLR192', 'T-9092');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Adriena', 'Petrello', 'China', 'PLR193', 'T-9093');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Alexi', 'Gors', 'China', 'PLR194', 'T-9094');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Atlante', 'McGinnis', 'United States', 'PLR195', 'T-9095');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Murry', 'Sandiford', 'Indonesia', 'PLR196', 'T-9096');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Phillie', 'Laurisch', 'China', 'PLR197', 'T-9097');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Joleen', 'Burel', 'Sweden', 'PLR198', 'T-9098');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Lilah', 'Caitlin', 'North Korea', 'PLR199', 'T-9099');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Ursulina', 'Dench', 'Greece', 'PLR200', 'T-9100');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Tammie', 'Barnbrook', 'Brazil', 'PLR201', 'T-9101');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Rudd', 'Bonsale', 'China', 'PLR202', 'T-9102');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Fawne', 'Relf', 'Portugal', 'PLR203', 'T-9103');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Neall', 'Mallord', 'Indonesia', 'PLR204', 'T-9104');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Lars', 'Edens', 'Philippines', 'PLR205', 'T-9105');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Anica', 'Dobbin', 'Brazil', 'PLR206', 'T-9106');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Dorry', 'Landrieu', 'Philippines', 'PLR207', 'T-9107');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Ber', 'Agron', 'China', 'PLR208', 'T-9108');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Angelia', 'Quakley', 'Indonesia', 'PLR209', 'T-9109');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Dagny', 'Goulstone', 'Pakistan', 'PLR210', 'T-9110');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Laurie', 'Abrehart', 'Israel', 'PLR211', 'T-9111');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Giavani', 'Bennedick', 'Thailand', 'PLR212', 'T-9112');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Tiena', 'Dodshon', 'Nepal', 'PLR213', 'T-9113');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Tamqrah', 'Fontanet', 'Russia', 'PLR214', 'T-9114');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Jedediah', 'Loverock', 'Indonesia', 'PLR215', 'T-9115');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Sylvan', 'Meiningen', 'Mongolia', 'PLR216', 'T-9116');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Clerissa', 'Malam', 'Macedonia', 'PLR217', 'T-9117');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Lacey', 'Strafford', 'China', 'PLR218', 'T-9118');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Welby', 'Lace', 'Mozambique', 'PLR219', 'T-9119');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Jillene', 'Baglow', 'China', 'PLR220', 'T-9120');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Tedman', 'Picford', 'China', 'PLR221', 'T-9121');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Weber', 'Happer', 'Ukraine', 'PLR222', 'T-9122');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Bernardina', 'Plain', 'Madagascar', 'PLR223', 'T-9123');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Hersh', 'Filler', 'China', 'PLR224', 'T-9124');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Eddy', 'Asbrey', 'China', 'PLR225', 'T-9125');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Cybill', 'Shilito', 'Spain', 'PLR226', 'T-9126');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Chloe', 'Anten', 'Russia', 'PLR227', 'T-9127');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Sherwynd', 'Von Brook', 'French Guiana', 'PLR228', 'T-9128');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Sinclare', 'Dodshon', 'Vietnam', 'PLR229', 'T-9129');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Kiley', 'Blackeby', 'Russia', 'PLR230', 'T-9130');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Bald', 'Eva', 'Indonesia', 'PLR231', 'T-9131');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Kirstyn', 'Tasch', 'China', 'PLR232', 'T-9132');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Boniface', 'Woolcocks', 'Canada', 'PLR233', 'T-9133');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Bobinette', 'Pounder', 'China', 'PLR234', 'T-9134');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Shayna', 'Breeze', 'Haiti', 'PLR235', 'T-9135');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Auroora', 'Kunz', 'Japan', 'PLR236', 'T-9136');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Jeramey', 'Chisholme', 'France', 'PLR237', 'T-9137');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Hercules', 'Hodjetts', 'China', 'PLR238', 'T-9138');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Marilin', 'Selwin', 'Portugal', 'PLR239', 'T-9139');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Mal', 'Elleton', 'Palestinian Territory', 'PLR240', 'T-9140');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Doti', 'Merle', 'Indonesia', 'PLR241', 'T-9141');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Jillene', 'Beidebeke', 'Afghanistan', 'PLR242', 'T-9142');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Seymour', 'Calderon', 'Sweden', 'PLR243', 'T-9143');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Devina', 'Dinnage', 'Brazil', 'PLR244', 'T-9144');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Chrystal', 'Goodnow', 'China', 'PLR245', 'T-9145');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Filide', 'Brame', 'Peru', 'PLR246', 'T-9146');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Brandy', 'Fardon', 'Czech Republic', 'PLR247', 'T-9147');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Nani', 'Sallarie', 'Canada', 'PLR248', 'T-9148');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Roselle', 'Larman', 'China', 'PLR249', 'T-9149');
INSERT INTO players (first_name, last name, country, id_player, id_team) VALUES ('Craggie', 'Skypp', 'China', 'PLR250', 'T-9150');
