CREATE TABLE teams 
(
    Club	varchar(300),
    id_team	varchar(300),
    id_stadium	varchar(300)
);

INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Almería', 'T-9001', 'STD-2101');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Athletic Bilbao', 'T-9002', 'STD-2102');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Atlético Madrid', 'T-9003', 'STD-2103');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Barcelona', 'T-9004', 'STD-2104');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Cádiz', 'T-9005', 'STD-2105');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Celta Vigo', 'T-9006', 'STD-2106');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Elche', 'T-9007', 'STD-2107');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Espanyol', 'T-9008', 'STD-2108');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Getafe', 'T-9009', 'STD-2109');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Girona', 'T-9010', 'STD-2110');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Mallorca', 'T-9011', 'STD-2111');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Osasuna', 'T-9012', 'STD-2112');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Rayo Vallecano', 'T-9013', 'STD-2113');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Real Betis', 'T-9014', 'STD-2114');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Real Madrid', 'T-9015', 'STD-2115');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Real Sociedad', 'T-9016', 'STD-2116');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Sevilla', 'T-9017', 'STD-2117');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Valencia', 'T-9018', 'STD-2118');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Valladolid', 'T-9019', 'STD-2119');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Villarreal', 'T-9020', 'STD-2120');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Arsenal', 'T-9021', 'STD-2121');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Aston Villa', 'T-9022', 'STD-2122');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Barnsley', 'T-9023', 'STD-2123');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Birmingham City', 'T-9024', 'STD-2124');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Blackburn Rovers', 'T-9025', 'STD-2125');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Blackpool', 'T-9026', 'STD-2126');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Bolton Wanderers', 'T-9027', 'STD-2127');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Bournemouth', 'T-9028', 'STD-2128');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Bradford City', 'T-9029', 'STD-2129');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Brentford', 'T-9030', 'STD-2130');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Brighton & Hove Albion', 'T-9031', 'STD-2131');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Burnley', 'T-9032', 'STD-2132');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Cardiff City', 'T-9033', 'STD-2133');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Charlton Athletic', 'T-9034', 'STD-2134');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Chelsea', 'T-9035', 'STD-2135');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Coventry City', 'T-9036', 'STD-2136');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Crystal Palace', 'T-9037', 'STD-2137');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Derby County', 'T-9038', 'STD-2138');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Everton', 'T-9039', 'STD-2139');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Fulham', 'T-9040', 'STD-2140');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Huddersfield Town', 'T-9041', 'STD-2141');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Hull City', 'T-9042', 'STD-2142');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Ipswich Town', 'T-9043', 'STD-2143');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Leeds United', 'T-9044', 'STD-2144');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Leicester City', 'T-9045', 'STD-2145');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Liverpool', 'T-9046', 'STD-2146');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Manchester City', 'T-9047', 'STD-2147');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Manchester United', 'T-9048', 'STD-2148');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Middlesbrough', 'T-9049', 'STD-2149');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Newcastle United', 'T-9050', 'STD-2150');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Norwich City', 'T-9051', 'STD-2151');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Nottingham Forest', 'T-9052', 'STD-2152');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Oldham Athletic', 'T-9053', 'STD-2153');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Portsmouth', 'T-9054', 'STD-2154');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Queens Park Rangers', 'T-9055', 'STD-2155');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Reading', 'T-9056', 'STD-2156');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Sheffield United', 'T-9057', 'STD-2157');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Sheffield Wednesday', 'T-9058', 'STD-2158');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Southampton', 'T-9059', 'STD-2159');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Stoke City', 'T-9060', 'STD-2160');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Sunderland', 'T-9061', 'STD-2161');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Swansea City', 'T-9062', 'STD-2162');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Swindon Town', 'T-9063', 'STD-2163');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Tottenham Hotspur', 'T-9064', 'STD-2164');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Watford', 'T-9065', 'STD-2165');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('West Bromwich Albion', 'T-9066', 'STD-2166');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('West Ham United', 'T-9067', 'STD-2167');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Wigan Athletic', 'T-9068', 'STD-2168');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('FC Augsburgb', 'T-9069', 'STD-2169');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Bayer Leverkusenb', 'T-9070', 'STD-2170');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Bayern Munichb', 'T-9071', 'STD-2171');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('VfL Bochum', 'T-9072', 'STD-2172');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Borussia Dortmunda', 'T-9073', 'STD-2173');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Borussia Mönchengladbach', 'T-9074', 'STD-2174');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Eintracht Frankfurta', 'T-9075', 'STD-2175');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('SC Freiburg', 'T-9076', 'STD-2176');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Hertha BSCa', 'T-9077', 'STD-2177');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Hoffenheimb', 'T-9078', 'STD-2178');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('FC Kölna', 'T-9079', 'STD-2179');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('RB Leipzigb', 'T-9080', 'STD-2180');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Mainz', 'T-9081', 'STD-2181');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Schalke', 'T-9082', 'STD-2182');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('VfB Stuttgarta', 'T-9083', 'STD-2183');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Union Berlinb', 'T-9084', 'STD-2184');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Werder Bremena', 'T-9085', 'STD-2185');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('VfL Wolfsburgb', 'T-9086', 'STD-2186');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Ajaccio', 'T-9087', 'STD-2187');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Angers', 'T-9088', 'STD-2188');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Auxerre', 'T-9089', 'STD-2189');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Brest', 'T-9090', 'STD-2190');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Clermont', 'T-9091', 'STD-2191');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Lens', 'T-9092', 'STD-2192');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Lille', 'T-9093', 'STD-2193');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Lorient', 'T-9094', 'STD-2194');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Lyon', 'T-9095', 'STD-2195');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Marseille', 'T-9096', 'STD-2196');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Monaco', 'T-9097', 'STD-2197');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Montpellier', 'T-9098', 'STD-2198');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Nantes', 'T-9099', 'STD-2199');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Nice', 'T-9100', 'STD-2200');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Paris Saint-Germain', 'T-9101', 'STD-2201');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Reims', 'T-9102', 'STD-2202');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Rennes', 'T-9103', 'STD-2203');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Strasbourg', 'T-9104', 'STD-2204');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Toulouse', 'T-9105', 'STD-2205');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Troyes', 'T-9106', 'STD-2206');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Atalanta', 'T-9107', 'STD-2207');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Bologna', 'T-9108', 'STD-2208');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Cremonese', 'T-9109', 'STD-2209');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Empoli', 'T-9110', 'STD-2210');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Fiorentina', 'T-9111', 'STD-2211');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Hellas Verona', 'T-9112', 'STD-2212');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Inter Milan', 'T-9113', 'STD-2213');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Juventus', 'T-9114', 'STD-2214');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Lazio', 'T-9115', 'STD-2215');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Lecce', 'T-9116', 'STD-2216');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('AC Milan', 'T-9117', 'STD-2217');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Monza', 'T-9118', 'STD-2218');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Napoli', 'T-9119', 'STD-2219');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Roma', 'T-9120', 'STD-2220');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Salernitana', 'T-9121', 'STD-2221');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Sampdoria', 'T-9122', 'STD-2222');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Sassuolo', 'T-9123', 'STD-2223');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Spezia', 'T-9124', 'STD-2224');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Torino', 'T-9125', 'STD-2225');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Udinese', 'T-9126', 'STD-2226');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Aldosivi', 'T-9127', 'STD-2227');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Argentinos Juniors', 'T-9128', 'STD-2228');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Atlético Tucumán', 'T-9129', 'STD-2229');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Banfield', 'T-9130', 'STD-2230');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Belgrano', 'T-9131', 'STD-2231');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Talleres', 'T-9132', 'STD-2232');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Boca Juniors', 'T-9133', 'STD-2233');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Colón', 'T-9134', 'STD-2234');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Defensa y Justicia', 'T-9135', 'STD-2235');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Estudiantes', 'T-9136', 'STD-2236');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Gimnasia y Esgrima', 'T-9137', 'STD-2237');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Godoy Cruz', 'T-9138', 'STD-2238');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Huracán', 'T-9139', 'STD-2239');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Independiente', 'T-9140', 'STD-2240');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Lanús', 'T-9141', 'STD-2241');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Newell\'s Old Boys', 'T-9142', 'STD-2242');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Patronato', 'T-9143', 'STD-2243');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Racing Club', 'T-9144', 'STD-2244');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('River Plate', 'T-9145', 'STD-2245');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Rosario Central', 'T-9146', 'STD-2246');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('San Lorenzo de Almagro', 'T-9147', 'STD-2247');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('San Martín', 'T-9148', 'STD-2248');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Tigre', 'T-9149', 'STD-2249');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Unión', 'T-9150', 'STD-2250');
INSERT INTO teams (Club, id_team, id_stadium) VALUES ('Vélez Sársfield', '', 'STD-2251');
